project_name: KerasSpiking
pkg_name: keras_spiking
repo_name: nengo/keras-spiking

description: Spiking neuron integration for Keras
copyright_start: 2020

license_rst: {}

contributing_rst: {}

contributors_rst: {}

manifest_in: {}

setup_cfg:
  pytest:
    xfail_strict: True
  pylint:
    disable:
      - no-value-for-parameter # https://github.com/tensorflow/tensorflow/issues/43038
    known_third_party:
      - tensorflow
  codespell:
    ignore_words:
      - hist

docs_conf_py:
  nengo_logo: ""
  extensions:
    - nengo_sphinx_theme.ext.autoautosummary
  tagmanager_id: GTM-KWCR2HN
  doctest_setup:
    - import numpy as np
    - import tensorflow as tf
  autoautosummary_change_modules:
    keras_spiking:
      - keras_spiking.layers.SpikingActivationCell
      - keras_spiking.layers.SpikingActivation
      - keras_spiking.layers.LowpassCell
      - keras_spiking.layers.Lowpass
      - keras_spiking.layers.AlphaCell
      - keras_spiking.layers.Alpha
      - keras_spiking.model_energy.ModelEnergy

ci_scripts:
  - template: static
  - template: test
    coverage: true
    pip_install:
      - $TF_VERSION
      - $NUMPY_VERSION
      - nengo[tests]
      - tensorflow-probability
  - template: docs
    pip_install:
      - $TF_VERSION
      - $NUMPY_VERSION
  - template: examples
    pip_install:
      - $TF_VERSION
      - $NUMPY_VERSION
  - template: remote-script
    remote_script: docs
    output_name: remote-docs
    host: azure-docs
    travis_var_key: 2895d60e3414
    azure_name: nengo-dl-docs
    azure_group: nengo-ci
    remote_vars:
      NUMPY_VERSION: $NUMPY_VERSION
      TF_VERSION: $TF_VERSION
    remote_setup:
      - conda install -y -c conda-forge cudatoolkit=11.3 cudnn=8.2
      - export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$CONDA_PREFIX/lib
  - template: remote-script
    remote_script: examples
    output_name: remote-examples
    host: azure-examples
    travis_var_key: 2895d60e3414
    azure_name: nengo-dl-examples
    azure_group: nengo-ci
    remote_vars:
      NUMPY_VERSION: $NUMPY_VERSION
      TF_VERSION: $TF_VERSION
    remote_setup:
      - conda install -y -c conda-forge cudatoolkit=11.3 cudnn=8.2
      - export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$CONDA_PREFIX/lib
  - template: deploy

travis_yml:
  python: 3.8
  global_vars:
    NUMPY_VERSION: numpy>=1.16.0
    TF_VERSION: tensorflow
  jobs:
    - stage: basic
      script: static
    - script: test
    - script: test
      env:
        TF_VERSION: tensorflow==2.1.0
        NUMPY_VERSION: numpy==1.16.0
      python: 3.6
    - stage: advanced
      script: remote-docs
    - script: remote-examples
  pypi_user: __token__
  deploy_dists:
    - sdist
    - bdist_wheel
  slack_notifications: "W/koGuFtOoRb9HFEVJrwMtevuZ24v8gJXLfFLobV2oVY+oz04K5GlRIVhtk\
    c8MwlJ+id/Haqa/eWvF2JZRg6GNfkHvX8QeGuB+LDNVg+pimYDA2di+itUEhEZsbJvOgajng7qvy9NV\
    fU2EFht9f3sWFoxQNc7szCpnSEAUHlFjzTEAduunYkRnJyyLsw9ytgxHf6zz0S9jnTdfqLbHqv/yhgj\
    ZkqXwLPJjkD4cKwVri63DzJSrZ1Tj8vSzJ31IWepCe/TIg5NXg1ml2ZKOWrnPGzWTy9RLmEw6H8v3jh\
    z9tqCwNCpH8ieqqRhLrxcmvYatOWSkgDlaLyK9W+ipsgT/ACM7Bh2pXRpNYnCe5BUqwN362dBlOgZ2c\
    /r7c6h1DfylEKwiD5VOqNNNYwBczq4klohK+o2tveXa1lN+wbPsxURpGQOsAgvvNmQbb0Cwhla7j6Q9\
    agHOJGaK3GEIhdi10oH/wLpGFlMYY2eJ6RCZfKQHey/Gs+5Vs4WhRtzLlG03KOKyBcOzyPw/06NDmh5\
    CNJPg6g95kxn4ZQXk1MxVndE5/M0A7idyGH1XOvJm7XF9928gOJ4cvXamBi1r3EqeM1tlVGdL+n2tzH\
    m2+S+RplYpkNzeE7zmHIUqpKEJeO6JRMLQcKs4VASwKk8zXLJ+Ps3tRsMsTGAyQxepuUilM="

codecov_yml:
  abs_target: 100%

setup_py:
  include_package_data: True
  install_req:
    - numpy>=1.16.0
    - packaging>=20.0
    - tensorflow>=2.1.0
  optional_req:
    - tensorflow-probability>=0.11.0
  docs_req:
    - jupyter>=1.0.0
    - matplotlib>=2.0.0
    - nbsphinx>=0.3.5
    - nengo-dl>=3.4.0
    - nengo-loihi>=1.0.0
    - nengo-sphinx-theme>=1.2.1
    - numpydoc>=0.6.0
    - sphinx>=3.0.0
  tests_req:
    - pylint>=1.9.2
    - pytest>=3.6.0
    - pytest-allclose>=1.0.0
    - pytest-cov>=2.6.0
    - pytest-rng>=1.0.0
    - pytest-xdist>=1.16.0
  classifiers:
      - "Development Status :: 3 - Alpha"
      - "Intended Audience :: Science/Research"
      - "License :: Free for non-commercial use"
      - "Operating System :: Microsoft :: Windows"
      - "Operating System :: POSIX :: Linux"
      - "Programming Language :: Python"
      - "Programming Language :: Python :: 3.6"
      - "Programming Language :: Python :: 3.7"
      - "Programming Language :: Python :: 3.8"
      - "Topic :: Scientific/Engineering"
      - "Topic :: Scientific/Engineering :: Artificial Intelligence"

pyproject_toml: {}

pre_commit_config_yaml: {}

version_py:
  major: 0
  minor: 3
  patch: 0
  release: true
